---
- name: Configuração completa do servidor EcoMeal
  hosts: all
  become: true

  vars:

    workspace: /home/vagrant/ecomeal-workspace

    repositories:

      - name: ecomeal-frontend
        url: https://github.com/alexikeda-ifsp/ecomeal-frontend.git

      - name: ecomeal-paciente-service
        url: https://github.com/alexikeda-ifsp/ecomeal-paciente-service.git

      - name: ecomeal-planoalimentar-service
        url: https://github.com/alexikeda-ifsp/ecomeal-planoalimentar-service.git

      - name: ecomeal-recomendacao-service
        url: https://github.com/alexikeda-ifsp/ecomeal-recomendacao-service.git


  tasks:
    #
    # Dependências básicas
    #
    - name: Atualizar apt
      apt:
        update_cache: yes

    - name: Instalar dependências
      apt:
        name:
          - git
          - curl
          - unzip
          - ca-certificates
          - gnupg
          - lsb-release
        state: present

    #
    # Docker
    #
    - name: Criar diretório keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Adicionar chave Docker
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Adicionar repositório Docker
      apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu
          jammy stable
        state: present

    - name: Instalar Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Iniciar Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Adicionar vagrant ao grupo docker
      user:
        name: vagrant
        groups: docker
        append: yes


    #
    # Workspace
    #
    - name: Criar workspace
      file:
        path: "{{ workspace }}"
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'


    #
    # Clonar serviços
    #
    - name: Clonar serviços EcoMeal
      git:
        repo: "{{ item.url }}"
        dest: "{{ workspace }}/{{ item.name }}"
        version: HEAD
        update: yes
        force: yes
      loop: "{{ repositories }}"


    #
    # Variáveis do ambiente
    #
    - name: Criar arquivo .env do Docker Compose
      copy:
        remote_src: yes
        src: "{{ workspace }}/config/.env.example"
        dest: "{{ workspace }}/.env"
        owner: vagrant
        group: vagrant
        mode: '0644'

    #
    # Docker Compose
    #
    - name: Verificar Docker
      become: false
      command:
        docker --version

    - name: Verificar Docker Compose
      become: false
      command:
        docker compose version

    - name: Subir ambiente EcoMeal
      become: false
      command:
        cmd: docker compose up -d --build
        chdir: "{{ workspace }}"

        